services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - coolify
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
networks:
  coolify:
    external: true